services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splitup-frontend-dev
    volumes:
      - frontend-dist:/app/dist
    restart: unless-stopped
    networks:
      - splitup-network

volumes:
  frontend-dist:
    name: splitup-frontend-dist

networks:
  splitup-network:
    external: true
    name: splitup-network
